#ifndef VDPM_CONFIG_H
#define VDPM_CONFIG_H

#define VDPM_RENDERER_OPENGL
#define VDPM_RENDERER_OPENGL_VBO
#define VDPM_RENDERER_OPENGL_VBO_MAP_VGEOM
#define VDPM_RENDERER_OPENGL_IBO
#define VDPM_ORIENTED_AWAY
#define VDPM_GEOMORPHS
#define VDPM_GEOMORPHS_PLUS
#define VDPM_REGULATION
//#define VDPM_REGULATION_FORCE
#define VDPM_AMORTIZATION
#define VDPM_TSTRIP_SWAP
//#define VDPM_TSTRIP_RESTRIP_ALL
//#define VDPM_PREDICT_VIEW_POSITION
//#define VDPM_SCREEN_ERROR_STRICT
#define VDPM_REUSE_OBJECTS
#define VDPM_BOUNDS
#define VDPM_MAX_ATTRIBS 5

#endif // VDPM_CONFIG_H
